### PR TITLE
Implement Intent.FLAG_ACTIVITY_NEW_TASK handling 

### LINKED ISSUE #11: Crash on Android 9.0 when using this library outside of an Activity
android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
        at android.app.ContextImpl.startActivity(ContextImpl.java:1072)
        at android.app.ContextImpl.startActivity(ContextImpl.java:1041)

With Android 9, you cannot start an activity from a non-activity context unless you pass the intent flag FLAG_ACTIVITY_NEW_TASK. If you attempt to start an activity without passing this flag, the activity does not start, and the system prints a message to the log.

### PR DESCRIPTION
**Pull request by polesapart**
This is needed for non-activity contexts. This should close #11 if adequately documented.

### CODE REVIEW

**Comment by nabinbhandari** [comment]
Great job. But you missed a null check. I've merged, fixed and published it to a new version.

**Comment by polesapart** [comment]
Nice catch!

**Comment by AliAzaz** [comment]
Still i'm getting this error :
> Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?

It's non-activity class and my code is:

    String[] permissions = {Manifest.permission.ACCESS_FINE_LOCATION, Manifest.permission.ACCESS_COARSE_LOCATION};
        Permissions.check(MainApp.getmContext(), permissions, null/*rationale*/, null/*options*/, new PermissionHandler() {
            @Override
            public void onGranted() {
                // do your task.
                Toast.makeText(MainApp.getmContext(), "Granted", Toast.LENGTH_SHORT).show();
            }

            @Override
            public void onDenied(Context context, ArrayList<String> deniedPermissions) {
                Toast.makeText(MainApp.getmContext(), "Denied", Toast.LENGTH_SHORT).show();
            }
        });

The error is coming on **Permissions.check** line.

Please give me the solution ASAP...

**Comment by soenkegissel** [comment]
I get this error too.
Sorry, can only supply you with obfocusated class: com.nabinbhandari.android.permissions.b.a (Unknown source: 129)

**Comment by nabinbhandari** [comment]
@AliAzaz @soenkegissel To solve this problem, pass `new Options().setCreateNewTask(true)` instead of '`null`' to the parameter '`options`'.

**Pull request merged**
