### PR TITLE
Check() with Application context

### PR DESCRIPTION
**Pull request by Nailik**

### CODE REVIEW

**Comment by nabinbhandari** [comment]
Hello there,

I checked the current code and I cannot reproduce the problem.

Please post a minimal code to reproduce the crash so that I can have a look at it.

**Comment by Nailik** [comment]
Hi,
when i use it like with Application context it crashes on Android 6. 
like:
`Permissions.check(application, new String[]{
                        Manifest.permission.WRITE_EXTERNAL_STORAGE},
                "....",
                new Permissions.Options()
                        .setSettingsDialogTitle("...").setRationaleDialogTitle("..."),
                initPermissionHandler(permissionHandler)
        );`
where application is typeof `android.app.Application`.

**Comment by nabinbhandari** [comment]
I am still unable to reproduce the crash. Please post the stacktrace too.

**Comment by Nailik** [comment]
`Caused by: android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
 at com.nabinbhandari.android.permissions.Permissions.check(Permissions.java:118)`
on Android 6.0 devices

**Comment by nabinbhandari** [comment]
Hello, I am extremely sorry for the late response.

While I appreciate your efforts, I still am unable to reproduce the crashes. Please provide me with a minimal code that leads to these crashes.

**Pull request closed without merging**
